### ISSUE TITLE
[Feature] Kudo support

### ISSUE THREAD

**Issue by platten** [kubermatic/kubecarrier#425]
**Is your feature request related to a problem? Please describe.**
Putting together a robust operator requires a lot of work. If you have many applications which need custom operators, then significant resources need to be allocated for operator development and maintenance. As [KUDO ](https://github.com/kudobuilder/kudo) is declarative by nature, it would be a good solution for addressing this pinpoint in a scalable manner.

**Describe the solution you'd like**
Added support for Kudo when adding a catalog and configuring the operator (with documentation and an example).

**Describe alternatives you've considered**
Extending the Kubeapps's platform's operator support to handle Kudo parameters.

**Additional context**

**Comment by thetechnick** [comment]
Hi @platten!

KubeCarrier is build on the premise that the underlying Operator uses a CRD to describe deployed instances. If I understand it correctly, KUDO has a single `Instance` CRD, with dynamic content, right?

This would necessitate to have some kind of adapter CRD that would allow a KUDO Operator to be used like any other Operator, because KubeCarrier needs dedicated CRD types to work with - e.g. for setting up RBAC.

Our team does not have any experience with KUDO yet.
So it would be great, if you could share ideas, on how you would like to see KUDO integrated.
